### ISSUE TITLE
Pagination index on search result page

### ISSUE THREAD

**Issue by canaryGrapher** [canaryGrapher/project-anant#38]
The last index on the pagination bar duplicates when clicked on it. 

![image](https://user-images.githubusercontent.com/27415791/204082637-241e9642-4d85-42ce-80c0-27b561424352.png)

**Comment by Parthiv-M** [comment]
To reproduce, search with T2=CN

![image](https://user-images.githubusercontent.com/57034486/204284299-5f267c07-96aa-4042-a6ef-530a871ecba7.png)
